---
 - name: grafana install
   hosts: 192.168.19.152
   become: yes
   become_method: su
   become_user: root
   tasks:
    - name: update respositories
      shell:
       cmd: apt update

    - name: install gnupg
      shell:
       cmd: apt install -y gnupg

    - name: add key
      ansible.builtin.apt_key:
       url: https://packages.grafana.com/gpg.key

    - name: add link to sources
      shell:
       cmd: echo "deb https://packages.grafana.com/oss/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list

    - name: update respos
      shell:
       cmd: apt update

    - name: install grafana
      shell:
       cmd: apt install -y grafana

    - name: start grafana
      shell:
       cmd: systemctl start grafana-server.service

    - name: enable on boot
      shell:
       cmd: systemctl enable grafana-server.service